#!/usr/bin/env python3
"""
profile-memory-slim-daily v1 (2026-06-19)
===========================================

Daily cron-driven memory slim for all 7 Hermes profiles.
Runs at 03:00 UTC (11:00 Beijing) via hermes cron (no_agent mode).

Logic:
1. For each profile in PROFILES, read its MEMORY.md file.
2. Compute char count + status:
   - healthy:   < 2,400  (80%)  → skip
   - warning:   2,400-2,850 (80-95%) → log, no action
   - critical:  ≥ 2,850 (95%)  → take action
3. Action for critical:
   - Backup MEMORY.md → <profile>/memories/MEMORY.md.bak.<ts>
   - Identify the LAST 2 entries (assume they are most recently added
     and most likely C-class facts / events).
   - POST each entry body to knowledge-base as a separate doc, with
     metadata.agent_id = <profile>'s memory_aid.
   - Remove those 2 entries from MEMORY.md (split by § separator).
   - Append ONE consolidated see-also index entry pointing to the
     new doc_ids.
4. If profile has no MEMORY.md, log "no memory file" and skip.
5. Print report. Cron delivers stdout to feishu:oc_c653562b.

Cross-profile safety:
- Only writes to the profile's own MEMORY.md and to knowledge-base
  docs tagged with metadata.agent_id=<this profile>'s memory_aid.
- No cross-profile writes.

NEVER touch:
- /home/a18845560182/.hermes/config.yaml
- ~/.hermes/profiles/<X>/config.yaml
- Other profiles' MEMORY.md files
- Anything in /home/a18845560182/.hermes/auth.json
- The default profile's own MEMORY.md when it is the one being slimmed
  IF the change would push a redline rule (use heuristic: if a §
  block contains "红线" or "永不松" or "派工铁律" or "飞书架构",
  treat as A-class and DO NOT touch).

This script is invoked by hermes cron "profile-memory-slim-daily"
(no_agent=true, profile=default). It runs in the default profile's
context but iterates all profiles' files. The agent_id in
metadata.agent_id ensures the ingested docs land in the right
namespace (per the profile's MEMORY_DEFAULT_AGENT_ID).
"""

import os
import sys
import json
import shutil
import urllib.request
import urllib.error
from datetime import datetime, timezone

HERMES_HOME = os.path.expanduser("~/.hermes")
PROFILES = [
    ("default", "gc-hermes-default", "~/.hermes/memories/MEMORY.md"),
    ("chief-agent", "gc-hermes-chief", "~/.hermes/profiles/chief-agent/memories/MEMORY.md"),
    ("dev-worker", "gc-hermes-dev", "~/.hermes/profiles/dev-worker/memories/MEMORY.md"),
    ("pm-orchestrator", "gc-hermes-pm", "~/.hermes/profiles/pm-orchestrator/memories/MEMORY.md"),
    ("qa-worker", "gc-hermes-qa", "~/.hermes/profiles/qa-worker/memories/MEMORY.md"),
    ("researcher", "gc-hermes-researcher", "~/.hermes/profiles/researcher/memories/MEMORY.md"),
    ("social-operator", "gc-hermes-social", "~/.hermes/profiles/social-operator/memories/MEMORY.md"),
]

KB_URL = "http://127.0.0.1:18081/knowledge/ingest_text"
KB_TOKEN_FILE = "/home/a18845560182/knowledge_service/.env"

# A-class heuristic substrings: if a § block contains any of these,
# it is a redline/constraint and MUST NOT be slimmed.
A_CLASS_KEYWORDS = [
    "永不松", "派工铁律", "飞书架构", "红线", "BG 进程", "BG进程",
    "Drift", "drift", "secret", "redact",
]

# Slim-index marker: blocks containing this substring are themselves
# index entries generated by this script. They MUST NOT be slimmed in
# subsequent runs, otherwise the script will keep migrating its own
# index (infinite loop) and the user's doc_ids become unstable.
SLIM_INDEX_MARKER = "memory-slim-"

# Thresholds (bytes)
HEALTHY_LIMIT = 2400      # 80% of 3000
CRITICAL_LIMIT = 2850     # 95% of 3000
HARD_LIMIT = 3000


def read_kb_token():
    """Read KNOWLEDGE_SERVICE_ADMIN_TOKEN from local .env (not hardcoded)."""
    try:
        with open(KB_TOKEN_FILE) as f:
            for line in f:
                line = line.strip()
                if line.startswith("KNOWLEDGE_SERVICE_ADMIN_TOKEN="):
                    return line.split("=", 1)[1].strip().strip('"').strip("'")
    except FileNotFoundError:
        pass
    return None


def is_a_class(block: str) -> bool:
    """Heuristic: a § block is A-class (redline) if it contains any A-class keyword."""
    if SLIM_INDEX_MARKER in block:
        # Always protect the index entry itself from re-slimming
        return True
    return any(kw in block for kw in A_CLASS_KEYWORDS)


def split_blocks(memory_text: str) -> list:
    """Split MEMORY.md content by § separator, strip whitespace, drop empties."""
    blocks = [b.strip() for b in memory_text.split("§")]
    return [b for b in blocks if b]


def assemble(blocks: list) -> str:
    """Re-assemble blocks with § separator and trailing newline."""
    return "§\n".join(blocks) + ("\n" if blocks else "")


def ingest_to_kb(title: str, content: str, agent_id: str) -> str | None:
    """POST a doc to knowledge-base; return document_id on success.

    BUG FIX 2026-06-22: 同 v2 一样, 必须送 context 否则 doc 写入空 namespace.
    之前 v1 跑出来的"知识卡"都在 org=''/project='' 孤儿区, list 查不到.
    """
    token = read_kb_token()
    if not token:
        print(f"  WARN: no KB token in {KB_TOKEN_FILE}, skipping ingest", file=sys.stderr)
        return None
    payload = {
        "context": {
            "org_id": "gc-hermes",
            "project_id": "gc-hermes-config",
            "agent_id": agent_id,
            "role": agent_id.replace("gc-hermes-", ""),
        },
        "title": title,
        "content": content,
        "metadata": {
            "agent_id": agent_id,
            "source_type": "memory_slim_migration",
            "ingested_at": datetime.now(timezone.utc).isoformat(),
            "version": 1,
            "from_profile": "memory_slim_v1",
        },
    }
    req = urllib.request.Request(
        KB_URL,
        data=json.dumps(payload).encode(),
        headers={
            "Content-Type": "application/json",
            "X-Admin-Token": token,
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            body = json.loads(resp.read())
            if body.get("ok"):
                return body.get("data", {}).get("document_id")
    except (urllib.error.URLError, urllib.error.HTTPError, json.JSONDecodeError) as e:
        print(f"  WARN: KB ingest failed: {e}", file=sys.stderr)
    return None


def slim_profile(name: str, agent_id: str, mem_path: str) -> dict:
    """Slim one profile's MEMORY.md if critical. Returns report dict."""
    result = {
        "profile": name,
        "agent_id": agent_id,
        "path": mem_path,
        "status": "ok",
        "action": "none",
        "before": 0,
        "after": 0,
        "migrated_doc_ids": [],
    }
    path = os.path.expanduser(mem_path)
    if not os.path.exists(path):
        result["status"] = "no_memory_file"
        return result
    with open(path) as f:
        text = f.read()
    size = len(text)
    result["before"] = size

    if size < CRITICAL_LIMIT:
        # healthy or warning — no action
        result["action"] = "skipped" if size < HEALTHY_LIMIT else "warning_no_action"
        result["after"] = size
        return result

    # CRITICAL: take action
    blocks = split_blocks(text)
    if len(blocks) < 3:
        # cannot safely slim — need at least 3 blocks (1 A-class to keep, 2 to migrate)
        result["status"] = "too_few_blocks"
        result["action"] = "skipped_insufficient_blocks"
        result["after"] = size
        return result

    # Identify A-class blocks to PROTECT
    a_class_idx = [i for i, b in enumerate(blocks) if is_a_class(b)]
    # Identify candidates to MIGRATE: last 2 blocks that are NOT A-class
    candidates = []
    for i in range(len(blocks) - 1, -1, -1):
        if i in a_class_idx:
            continue
        candidates.append(i)
        if len(candidates) >= 2:
            break
    candidates.reverse()  # preserve original order
    if not candidates:
        result["status"] = "all_blocks_a_class"
        result["action"] = "skipped_protected"
        result["after"] = size
        return result

    # Backup
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    bak_path = f"{path}.bak.{ts}-slim"
    shutil.copy2(path, bak_path)

    # Migrate each candidate to knowledge-base
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    doc_ids = []
    for idx in candidates:
        block = blocks[idx]
        # Title: take first 60 chars of the block
        title_seed = block.split(":", 1)[0].strip()[:60] if ":" in block else block[:60]
        title = f"[memory-slim-{today}] {name}: {title_seed}"
        doc_id = ingest_to_kb(title, block, agent_id)
        if doc_id:
            doc_ids.append((doc_id, title))

    if not doc_ids:
        result["status"] = "kb_ingest_failed"
        result["action"] = "rolled_back_no_ingest"
        result["after"] = size
        # Restore from backup since nothing actually migrated
        shutil.copy2(bak_path, path)
        return result

    # Remove migrated blocks
    kept = [b for i, b in enumerate(blocks) if i not in candidates]
    # Build see-also index entry
    see_also = " | ".join(f"kb={did} {t.split(' ', 2)[-1][:40]}" for did, t in doc_ids)
    index_entry = f"memory-slim-{today} 索引:迁移 {len(doc_ids)} 条到知识库(已 commit search 可查)[see-also: {see_also}]"
    kept.append(index_entry)
    new_text = assemble(kept)
    with open(path, "w") as f:
        f.write(new_text)
    result["after"] = len(new_text)
    result["action"] = f"slimmed_{len(doc_ids)}_entries"
    result["migrated_doc_ids"] = [d for d, _ in doc_ids]
    result["backup"] = bak_path
    return result


def main():
    print(f"=== profile-memory-slim-daily run @ {datetime.now(timezone.utc).isoformat()} ===\n")
    results = [slim_profile(name, aid, path) for name, aid, path in PROFILES]
    # Summary
    print("\n=== Summary ===")
    for r in results:
        action = r["action"]
        before = r["before"]
        after = r["after"]
        delta = after - before
        print(f"  {r['profile']:20s} {r['status']:25s} {action:30s} {before:5d}→{after:5d} (Δ {delta:+5d} B)")
        if r.get("backup"):
            print(f"    backup: {r['backup']}")
        for did in r["migrated_doc_ids"]:
            print(f"    doc_id: {did}")
    # Final verdict
    any_critical = any(r["status"] == "ok" and r["action"].startswith("slimmed") for r in results)
    print()
    if any_critical:
        print("✅ Slim-down completed for ≥1 critical profile(s).")
    else:
        print("✓ All profiles within healthy range; no slim-down needed.")


if __name__ == "__main__":
    main()
